source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

# 网络环境测试
pod 'Reachability', '~>3.2'
# 公告通知时日历控件
pod 'JTCalendar', '~>1.2.3'
pod 'M13Checkbox', '~>1.1.2'
pod 'SKSplashView', '~>0.1.0'
pod 'MMMaterialDesignSpinner', '~>0.2.0'
pod 'SSZipArchive', '~>0.3.2'